# Generated by Django 4.2.4 on 2023-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('inv', models.IntegerField()),
                ('sale', models.DecimalField(decimal_places=2, max_digits=2)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_type', models.CharField(max_length=50)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
